---

- hosts: all
  become: true
  tasks:
  - name: "install apache2 Package"
    apt:
      name: apache2
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: "update OS"
    apt:
      update_cache: yes 
    when: ansible_distribution == "Ubuntu"
 
