---

- hosts: all
  become: true
  tasks:
 
  - name: Install php (Ubuntu)
    apt:
      name: 
      -  libapache2-mod-php


- hosts: db_server
  become: true
  tasks:
  
  - name: Install Apache (ubuntu)
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: Install MariaDb Package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install samba Package
    package:
      name: samba
      state: latest
