---

- hosts: all
  become: true
  roles:
    - base

- hosts: all
  become: true
  roles:
    - workstation

- hosts: all
  become: true
  roles:
    - web_server

- hosts: all
  become: true
  roles:
    - db_server
   
